[engine]
service-sleep = 1
process-sleep = 1
automatic-recover = false

[chain.dev]
chain-name = "Golem testnet"
chain-id = 987789
rpc-endpoints = ["http://127.0.0.1:8545"]
currency-symbol = "tETH"
priority-fee = 1.1
max-fee-per-gas = 500.0
gas-left-warning-limit = 1000000
transaction-timeout = 100
token = { address = "0xfff17584d526aba263025eE7fEF517E4A31D4246", symbol = "tGLM" }
multi-contract = { address = "0xF9861F83766CD507E0d2749B60d4fD6C68E5B96C", max-at-once = 10 }
confirmation-blocks = 1
faucet-eth-amount = 10.0
faucet-glm-amount = 20.0
block-explorer-url = "http://127.0.0.1:4000"
