services:
  payment:
    build:
      context: ..
      dockerfile: Dockerfile
    command: /bin/bash test_payments_1.sh
    environment:
      - ETH_PRIVATE_KEYS=f188692fd0f2e8e8af5478cb547245868f9cbae33f1a4aef3cf4912086057c2f
      - DB_SQLITE_FILENAME=db.sqlite
  geth:
    volumes:
      - ./genesis/:/runtime/tmp
    build:
      context: ../yatestnet
      dockerfile: Dockerfile
    command: python -u setup_chain.py
    ports:
      - '8545:8545'
    environment:
      - CHAIN_ID=987789
      - CHAIN_NAME=Golem test chain
      - CHAIN_TYPE=local
      - KEEP_RUNNING=1
      - SIGNER_ACCOUNT_PRIVATE_KEY=${SIGNER_ACCOUNT_PRIVATE_KEY}
      - MAIN_ACCOUNT_PRIVATE_KEY=${MAIN_ACCOUNT_PRIVATE_KEY}
      - SIGNER_ACCOUNT_KEYSTORE_PASSWORD=${SIGNER_ACCOUNT_KEYSTORE_PASSWORD}
      - FAUCET_ACCOUNT_PRIVATE_KEY=${FAUCET_ACCOUNT_PRIVATE_KEY}
      - FAUCET_ACCOUNT_PUBLIC_ADDRESS=${FAUCET_ACCOUNT_PUBLIC_ADDRESS}
      - GLM_CONTRACT_ADDRESS=${GLM_CONTRACT_ADDRESS}
      - MULTI_PAYMENT_CONTRACT_ADDRESS=${MULTI_PAYMENT_CONTRACT_ADDRESS}
      - DISTRIBUTE_CONTRACT_ADDRESS=${DISTRIBUTE_CONTRACT_ADDRESS}
      - PERIOD_IN_SECONDS_INT=2
