services:
  looper:
    image: ghcr.io/golemfactory/erc20_processor:latest
    command: erc20_processor run --http-addr 0.0.0.0 --http-port 9350 --http --keep-running --balance-check-loop 0
    working_dir: /looper
    volumes:
      - ../config-payments-goerli.toml:/looper/config-payments-local.toml
  prometheus:
    image: prom/prometheus
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3011:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning
