{
 "title": "Rpc Pool Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rpc_endpoint_effective_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Validation score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rpc_endpoint_score_validation", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Success requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rpc_endpoint_success_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rpc_endpoint_error_count", "legendFormat": "__auto" }
   ]
  }
 ]
}