[engine]
# proces interval (in seconds) is to set how often we want to recheck transaction status
# minimum 1 second, sensible maximum around 60 seconds
process-interval = 5
# proces interval after send (in seconds) is to set how long to wait after sending transaction before checking for confirmation
# sensible minimum 20 seconds, sensible maximum around 60 seconds
process-interval-after-send = 5
# proces interval after error (in seconds) is to set how long to wait after encountering error before trying again
# minimum 1 second, sensible maximum around 60 seconds
process-interval-after-error = 5

# proces interval after missing gas or token (in seconds)
# it is starting with checking every process-interval-after-no-gas-or-token-start
# and then increasing by multiplying by process-interval-after-no-gas-or-token-increase
# up to process-interval-after-no-gas-or-token-max
process-interval-after-no-gas-or-token-start = 5
process-interval-after-no-gas-or-token-max = 5
process-interval-after-no-gas-or-token-increase = 1.5

# report alive interval (in seconds) is to set how often we want to report that we are alive
# minimum 1 second, maximum is capped by gather-interval
report-alive-interval = 10
# gather interval (in seconds) is to set how often payments are gathered
# minimum 1 second, no maximum limit
gather-interval = 60
# gather payments on payment driver start (otherwise wait for first gather-interval)
gather-at-start = true
automatic-recover = false
# set to true to not respect deadlines attached to payments
ignore-deadlines = false

[chain.goerli]
chain-name = "Goerli"
chain-id = 5
currency-symbol = "tETH"
priority-fee = 0.000001
max-fee-per-gas = 10.0
gas-left-warning-limit = 1000000
transaction-timeout = 100
token = { address = "0x33af15c79d64b85ba14aaffaa4577949104b22e8", symbol = "tGLM" }
multi-contract = { address = "0x7777784f803a7bf1d7f115f849d29ce5706da64a", max-at-once = 10 }
faucet-client = { max-eth-allowed = 0.009, faucet-srv = "_eth-faucet._tcp", faucet-host = "faucet.testnet.golem.network", faucet-lookup-domain = "dev.golem.network", faucet-srv-port = 4001 }
mint-contract = { address = "0xCCA41b09C1F50320bFB41BD6822BD0cdBDC7d85C", max-glm-allowed = 400 }
confirmation-blocks = 0
block-explorer-url = "https://goerli.etherscan.io"

[[chain.goerli.rpc-endpoints]]
name = "eth-goerli.g.alchemy.com"
endpoint = "https://eth-goerli.g.alchemy.com/v2/demo"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.goerli.rpc-endpoints]]
name = "eth-goerli.public.blastapi.io"
endpoint = "https://eth-goerli.public.blastapi.io"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.goerli.rpc-endpoints]]
name = "eth-goerli.api.onfinality.io/public"
endpoint = "https://eth-goerli.api.onfinality.io/public"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.goerli.rpc-endpoints]]
name = "rpc.goerli.mudit.blog"
endpoint = "https://rpc.goerli.mudit.blog"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.goerli.rpc-endpoints]]
name = "endpoints.omniatech.io/v1/eth/goerli/public"
endpoint = "https://endpoints.omniatech.io/v1/eth/goerli/public"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.goerli.rpc-endpoints]]
name = "rpc.goerli.eth.gateway.fm"
endpoint = "https://rpc.goerli.eth.gateway.fm"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.goerli.rpc-endpoints]]
name = "goerli.blockpi.network/v1/rpc/public"
endpoint = "https://goerli.blockpi.network/v1/rpc/public"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.goerli.rpc-endpoints]]
name = "goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
endpoint = "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.goerli.rpc-endpoints]]
name = "rpc.ankr.com/eth_goerli"
endpoint = "https://rpc.ankr.com/eth_goerli"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.goerli.rpc-endpoints]]
name = "ethereum-goerli-rpc.allthatnode.com"
endpoint = "https://ethereum-goerli-rpc.allthatnode.com"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.goerli.rpc-endpoints]]
name = "rpc.slock.it/goerli"
endpoint = "https://rpc.slock.it/goerli"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.goerli.rpc-endpoints]]
name = "www.ethercluster.com/goerli"
endpoint = "https://www.ethercluster.com/goerli"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120

[[chain.goerli.rpc-endpoints]]
name = "rpc.ankr.com/eth_goerli"
endpoint = "https://rpc.ankr.com/eth_goerli"
priority = 0
max-timeout-ms = 5000
verify-interval-secs = 60
allowed-head-behind-secs = 120