[engine]
# proces interval (in seconds) is to set how often we want to recheck transaction status
# minimum 1 second, sensible maximum around 60 seconds
process-interval = 5
# proces interval after send (in seconds) is to set how long to wait after sending transaction before checking for confirmation
# sensible minimum 20 seconds, sensible maximum around 60 seconds
process-interval-after-send = 5
# proces interval after error (in seconds) is to set how long to wait after encountering error before trying again
# minimum 1 second, sensible maximum around 60 seconds
process-interval-after-error = 5

# proces interval after missing gas or token (in seconds)
# it is starting with checking every process-interval-after-no-gas-or-token-start
# and then increasing by multiplying by process-interval-after-no-gas-or-token-increase
# up to process-interval-after-no-gas-or-token-max
process-interval-after-no-gas-or-token-start = 5
process-interval-after-no-gas-or-token-max = 5
process-interval-after-no-gas-or-token-increase = 1.5

# report alive interval (in seconds) is to set how often we want to report that we are alive
# minimum 1 second, maximum is capped by gather-interval
report-alive-interval = 10
# gather interval (in seconds) is to set how often payments are gathered
# minimum 1 second, no maximum limit
gather-interval = 60
# gather payments on payment driver start (otherwise wait for first gather-interval)
gather-at-start = true
automatic-recover = false
# set to true to not respect deadlines attached to payments
ignore-deadlines = false

[chain.polygon]
chain-name = "Polygon mainnet"
chain-id = 137
currency-symbol = "MATIC"
priority-fee = 30.111
max-fee-per-gas = 500.0
gas-left-warning-limit = 1000000
transaction-timeout = 100
token = { address = "0x0B220b82F3eA3B7F6d9A1D8ab58930C064A2b5Bf", symbol = "GLM" }
# multi-contract = { address = "0x50100d4faf5f3b09987dea36dc2eddd57a3e561b", max-at-once = 10 }
confirmation-blocks = 1
block-explorer-url = "https://polygonscan.com"

[[chain.polygon.rpc-endpoints]]
name = "polygon-rpc.com"
endpoint = "https://polygon-rpc.com"
priority = 0
max-timeout-ms = 5000
allowed-head-behind-secs = 120

[[chain.polygon.rpc-endpoints]]
name = "maticvigil.com"
endpoint = "https://rpc-mainnet.maticvigil.com"
priority = 0
max-timeout-ms = 5000
allowed-head-behind-secs = 120

[[chain.polygon.rpc-endpoints]]
name = "quiknode.pro"
endpoint = "https://rpc-mainnet.matic.quiknode.pro"
priority = 0
max-timeout-ms = 5000
allowed-head-behind-secs = 120

[[chain.polygon.rpc-endpoints]]
name = "golem.network"
endpoint = "https://bor.golem.network"
priority = 0
max-timeout-ms = 5000
allowed-head-behind-secs = 120

[[chain.polygon.rpc-endpoints]]
name = "allthatnode.com-archive"
endpoint = "https://polygon-mainnet-archive.allthatnode.com:8545"
priority = 0
max-timeout-ms = 5000
allowed-head-behind-secs = 120

[[chain.polygon.rpc-endpoints]]
name = "allthatnode.com-norm"
endpoint = "https://polygon-mainnet-rpc.allthatnode.com:8545"
priority = 0
max-timeout-ms = 5000
allowed-head-behind-secs = 120
