name: Test

on: push

jobs:
  payment_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build tests
        run: cargo test --profile=release-fast --no-run

      - name: Run tests
        run: cargo test --profile=release-fast -- --test-threads=10
