name: Test

on: push

jobs:
  build_arm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and run tests
        run: cargo test --release --all
