name: CI

on: push

jobs:
  fmt_and_clippy:
    name: Fmt and clippy
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Clippy all
        run: cargo clippy --all-targets --all-features --all -- -D warnings

  erc20_processor:
    name: ERC20 processor build only
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build erc20 processor
        run: cargo build --profile=release-lto

  build_tests_and_cache:
    name: Build and cache all tests
    timeout-minutes: 20

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        profile: [release-fast, release-lto, dev]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "tests-${{ matrix.profile }}"

      - name: Build tests
        run: cargo test --profile=${{ matrix.profile }} --no-run

  payment_tests:
    name: Payment tests (basic + short ones)
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "tests-release-fast"
          save-if: false

      - name: Build tests
        run: cargo test --profile=release-fast --no-run

      - name: Run tests (docker_01_basic)
        run: cargo test --test docker_01_basic --profile=release-fast -- --test-threads=10

      - name: Run tests (docker_02_errors)
        run: cargo test --test docker_02_errors --profile=release-fast -- --test-threads=10

      - name: Run tests (docker_03_problems)
        run: cargo test --test docker_03_problems --profile=release-fast -- --test-threads=10
