name: Test

on: push

jobs:
  fmt_and_clippy:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Clippy all
        run: cargo clippy --all-targets --all-features --all -- -D warnings

  erc20_processor:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build erc20 processor
        run: cargo build --profile=release-lto

  payment_tests:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build tests
        run: cargo test --profile=release-fast --no-run

      - name: Run tests (docker_01_basic)
        run: cargo test --test docker_01_basic --profile=release-fast -- --test-threads=10

      - name: Run tests (docker_02_errors)
        run: cargo test --test docker_02_errors --profile=release-fast -- --test-threads=10

      - name: Run tests (docker_03_problems)
        run: cargo test --test docker_03_problems --profile=release-fast -- --test-threads=10

