name: Custom_10x_run

on:
  workflow_dispatch:
    inputs:
      build_profile:
        description: 'Build profile'
        required: true
        default: 'release-fast'
      transfer_count:
        description: 'Number of transfers to generate'
        required: true
        default: '100000'

jobs:
  payment_tests_long:
    name: Payment tests (long)
    timeout-minutes: 300

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run_no: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "test-cache-${{ github.event.inputs.build_profile }}"

      - name: Build tests (${{ github.event.inputs.build_profile }})
        run: cargo test --profile=${{ github.event.inputs.build_profile }} --test custom_long --no-run

      - name: Run tests (custom_long x ${{ github.event.inputs.transfer_count }})
        run: cargo test --profile=${{ github.event.inputs.build_profile }} --test custom_long -- --test-threads=1
        env:
          ERC20_LIB_USE_MEM_DB: 1
          TRANSFER_COUNT: ${{ github.event.inputs.transfer_count }}
