name: Frontend

on: push

jobs:
  build-frontend:
    name: Build frontend
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build frontend
        run: |
          cd frontend
          npm install

      - name: Run checks
        run: |
          cd frontend
          npm run check

      - name: Check prettier
        run: |
          cd frontend
          npm run prettier-check

      - name: Check lints
        run: |
          cd frontend
          npm run lint

      - name: Check build
        run: |
          cd frontend
          npm run build
