name: Frontend

on: push

jobs:
  build-frontend:
    name: Build frontend
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Pack assets
        run: |
          tar -czJf frontend.tar.xz frontend/dist

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend.tar.xz