name: Frontend

on: push

jobs:
  build-frontend:
    name: Build frontend
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd frontend
          yarn install --check-files

      - name: Run checks
        run: |
          cd frontend
          yarn run check

      - name: Check prettier
        run: |
          cd frontend
          yarn run prettier-check

      - name: Check lints
        run: |
          cd frontend
          yarn run lint

      - name: Check build
        run: |
          cd frontend
          yarn run build
