name: Transfers_10x100000

on:
  workflow_dispatch:
    inputs:
      transfer_count:
        description: 'Number of transfers to generate'
        required: true
        default: '10000'

jobs:
  payment_tests_long:
    name: Payment tests (long)
    timeout-minutes: 300

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run_no: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build tests (release-lto)
        run: cargo test --profile=release-lto --test docker_10_long --no-run

      - name: Run tests (docker_10_long)
        run: cargo test --profile=release-lto --test docker_10_long test_durability_100000 -- --test-threads=1
        env:
          USE_DISK_DB_INSTEAD_OF_MEM: 1
